# -*- coding: utf-8 -*-
"""Ocsanida Felicia Sihite_F0403251026_TTS 4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HE7XD92zLSU3q1g7QLJkDMbyJshclYRg
"""

def hitung_total_panen(hasil_panen):
    """Menghitung total hasil panen (dalam kg)."""
    return sum(hasil_panen)


if __name__ == "__main__":
    data = [120, 85, 200, 150]
    total = hitung_total_panen(data)
    print(f"Total hasil panen: {total} kg")